CREATE TABLE A(A NUMBER, B NUMBER);
INSERT INTO A(A, B) VALUES (NULL, 2);
SELECT SUM(A) FROM A GROUP BY A+B;
SELECT SUM(DISTINCT A) FROM A B WHERE B.B = (SELECT COUNT(*) FROM A WHERE A.B = B.B);
DROP TABLE A;

