CREATE SEQUENCE seq START WITH 1;

CREATE OR REPLACE TRIGGER dodajzespol BEFORE INSERT ON ZESPOLY FOR EACH ROW
BEGIN
  IF(:NEW.ID_ZESP IS NULL) THEN
    :NEW.ID_ZESP := seq.nextval;
  END IF;
END;

ALTER TABLE ZESPOLY ADD (LICZBA_PRACOWNIKOW NUMBER);
UPDATE ZESPOLY z SET LICZBA_PRACOWNIKOW = (SELECT COUNT(*) FROM PRACOWNICY WHERE ID_ZESP=z.ID_ZESP);
CREATE OR REPLACE TRIGGER pielegnuj AFTER INSERT OR UPDATE OR DELETE ON PRACOWNICY FOR EACH ROW
BEGIN
  UPDATE ZESPOLY z SET LICZBA_PRACOWNIKOW = (SELECT COUNT(*) FROM PRACOWNICY WHERE ID_ZESP=z.ID_ZESP);
END;

CREATE TABLE HISTORIA (
  ID_PRAC NUMBER,
  PLACA_POD NUMBER,
  ETAT VARCHAR2(20),
  ZESPOL VARCHAR2(20),
  MODYFIKACJA DATE);

CREATE OR REPLACE TRIGGER trhistoria BEFORE UPDATE ON PRACOWNICY FOR EACH ROW WHEN
  (OLD.ID_ZESP<>NEW.ID_ZESP OR OLD.ETAT<>NEW.ETAT OR OLD.PLACA_POD<>NEW.PLACA_POD)
DECLARE
  v_nazwa VARCHAR2(20);
BEGIN
  SELECT NAZWA INTO v_nazwa FROM ZESPOLY WHERE ID_ZESP=:OLD.ID_ZESP;
  INSERT INTO HISTORIA(ID_PRAC, PLACA_POD, ETAT, ZESPOL, MODYFIKACJA) VALUES
    (:OLD.ID_PRAC, :OLD.PLACA_POD, :OLD.ETAT, v_nazwa, CURRENT_DATE);
END;

CREATE OR REPLACE VIEW SZEFOWIE AS SELECT (SELECT r.NAZWISKO FROM PRACOWNICY r WHERE r.ID_PRAC=p.ID_SZEFA), COUNT(*) AS PRACOWNICY FROM PRACOWNICY p WHERE p.ID_SZEFA IS NOT NULL GROUP BY p.ID_SZEFA;


