CREATE OR REPLACE PROCEDURE PODWYZKA(zespol NUMBER, procent NUMBER) IS
  vtest NUMBER := NULL;
BEGIN
  SELECT COUNT(*) INTO vtest FROM ZESPOLY WHERE ID_ZESP=zespol;
  IF vtest=0 THEN RAISE_APPLICATION_ERROR(-20001, 'Brak zespołu o podanym numerze'); END IF;
  UPDATE PRACOWNICY SET PLACA_POD=PLACA_POD+(PLACA_POD*procent/100) WHERE ID_ZESP=zespol;
END;

CREATE OR REPLACE PROCEDURE LICZBA_PRACOWNIKOW(zespol IN VARCHAR2, liczba OUT NUMBER) IS
  vtest NUMBER := NULL;
BEGIN
  SELECT COUNT(*) INTO vtest FROM ZESPOLY WHERE NAZWA=zespol;
  IF vtest=0 THEN RAISE_APPLICATION_ERROR(-20001, 'Nieprawidłowa nazwa zespołu'); END IF;
  SELECT COUNT(*) INTO liczba FROM PRACOWNICY WHERE ID_ZESP=(SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA=zespol);
END;

CREATE OR REPLACE PROCEDURE NOWY_PRACOWNIK(nazw VARCHAR2, zesp VARCHAR2, szef VARCHAR2, placa NUMBER) IS
  vtest NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO vtest FROM ZESPOLY WHERE NAZWA=zesp;
  IF vtest=0 THEN RAISE_APPLICATION_ERROR(-20001, 'Nieprawidłowan nazwa zespołu'); END IF;
  SELECT COUNT(*) INTO vtest FROM PRACOWNICY WHERE NAZWISKO=szef;
  IF vtest=0 THEN RAISE_APPLICATION_ERROR(-20002, 'Nieprawidłowe nazwisko szefa'); END IF;
  INSERT INTO PRACOWNICY(NAZWISKO, ETAT, ID_SZEFA, ZATRUDNIONY, PLACA_POD, ID_ZESP) VALUES
    (nazw, 'STAZYSTA', (SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO=szef), CURRENT_DATE, placa,
     (SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA=zesp));
END;

CREATE OR REPLACE FUNCTION PLACA_NETTO(brutto NUMBER, podatek NUMBER DEFAULT 20) RETURN NUMBER IS
BEGIN
  RETURN brutto*((100-podatek)/100);
END;

CREATE OR REPLACE FUNCTION SILNIA(n NUMBER) RETURN NUMBER IS
  result NUMBER := 1;
BEGIN
  FOR i IN 1 .. n LOOP
    result:=result*i;
  END LOOP;
  RETURN result;
END;

CREATE OR REPLACE FUNCTION SILNIA(n NUMBER) RETURN NUMBER IS
BEGIN
  IF n = 1 THEN RETURN 1;
  ELSE RETURN n*SILNIA(n-1);
  END IF;
END;

CREATE OR REPLACE FUNCTION STAZ(z DATE) RETURN NUMBER IS
BEGIN
  RETURN FLOOR(MONTHS_BETWEEN(CURRENT_DATE, z)/12);
END;