SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY ORDER BY PLACA_POD DESC FETCH FIRST 3 ROWS ONLY;
SELECT NAZWISKO, PLACA_POD FROM (SELECT ROWNUM, NAZWISKO, PLACA_POD FROM PRACOWNICY ORDER BY PLACA_POD DESC) WHERE ROWNUM<=3;
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY ORDER BY PLACA_POD DESC OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;
SELECT NAZWISKO, PLACA_POD FROM (SELECT NUMER, NAZWISKO, PLACA_POD FROM (SELECT ROWNUM AS NUMER, NAZWISKO, PLACA_POD FROM PRACOWNICY ORDER BY PLACA_POD DESC) WHERE ROWNUM<=10) WHERE NUMER>5;
WITH PIOTROWO AS (SELECT ID_ZESP, NAZWA, ADRES FROM ZESPOLY WHERE ADRES='PIOTROWO 3A'), ASYSTENCI AS (SELECT NAZWISKO, ETAT, ID_ZESP FROM PRACOWNICY WHERE ETAT='ASYSTENT') SELECT NAZWISKO, ETAT, NAZWA, ADRES FROM ASYSTENCI NATURAL JOIN PIOTROWO;
WITH PODWLADNI (ID_PRAC, ID_SZEFA, NAZWISKO, POZIOM) AS (SELECT ID_PRAC, ID_SZEFA, NAZWISKO, 1 FROM PRACOWNICY WHERE NAZWISKO='BRZEZINSKI' UNION ALL SELECT p.ID_PRAC, p.ID_SZEFA, p.NAZWISKO, POZIOM+1 FROM PODWLADNI s JOIN PRACOWNICY p ON s.ID_PRAC=p.ID_SZEFA) SEARCH DEPTH FIRST BY NAZWISKO SET PORZADEK_POTOMKOW SELECT LPAD(NAZWISKO, POZIOM+LENGTH(NAZWISKO)-1) AS NAZWISKO, POZIOM FROM PODWLADNI ORDER BY PORZADEK_POTOMKOW;
SELECT LPAD(NAZWISKO, LENGTH(NAZWISKO)+LEVEL-1) AS NAZWISKO_, LEVEL AS POZIOM FROM PRACOWNICY CONNECT BY ID_SZEFA = PRIOR ID_PRAC START WITH NAZWISKO = 'BRZEZINSKI' ORDER SIBLINGS BY NAZWISKO;
