CREATE TABLE PROJEKTY(
  ID_PROJEKTU NUMBER(4) GENERATED ALWAYS AS IDENTITY, OPIS_PROJEKTU VARCHAR2(20),
  DATA_ROZPOCZECIA DATE DEFAULT CURRENT_DATE,
  DATA_ZAKONCZENIA DATE,
  FUNDUSZ NUMBER(7, 2));
INSERT INTO PROJEKTY(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ) VALUES ('Indeksy bitmapowe', DATE'1999-04-02', DATE'2001-08-31', 25000);
INSERT INTO PROJEKTY(OPIS_PROJEKTU, FUNDUSZ) VALUES ('Sieci kręgosłupowe', 19000);
SELECT ID_PROJEKTU, OPIS_PROJEKTU FROM PROJEKTY;
INSERT INTO PROJEKTY(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ) VALUES ('Indeksy drzewiaste', DATE'2013-12-24', DATE'2014-01-01', 1200);
UPDATE PROJEKTY SET ID_PROJEKTU=10 WHERE OPIS_PROJEKTU='Indeksy drzewiaste';
CREATE TABLE PROJEKTY_KOPIA AS SELECT * FROM PROJEKTY;
SELECT * FROM PROJEKTY_KOPIA;
INSERT INTO PROJEKTY_KOPIA(ID_PROJEKTU, OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ) VALUES (10, 'Sieci lokalne', CURRENT_DATE, CURRENT_DATE+INTERVAL '1' YEAR, 24500);
DELETE FROM PROJEKTY WHERE OPIS_PROJEKTU='Indeksy drzewiaste';
SELECT TABLE_NAME FROM USER_TABLES;
ALTER TABLE PROJEKTY MODIFY ID_PROJEKTU NUMBER(4) CONSTRAINT PK_PROJEKTY PRIMARY KEY;
ALTER TABLE PROJEKTY MODIFY OPIS_PROJEKTU VARCHAR2(20) NOT NULL CONSTRAINT UK_PROJEKTY UNIQUE;
ALTER TABLE PROJEKTY ADD CONSTRAINT SPRAWDZENIE CHECK(DATA_ROZPOCZECIA<DATA_ZAKONCZENIA);
ALTER TABLE PROJEKTY MODIFY FUNDUSZ NUMBER(6) CONSTRAINT WARTOSC CHECK (FUNDUSZ>0);
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='PROJEKTY';
INSERT INTO PROJEKTY(OPIS_PROJEKTU, FUNDUSZ) VALUES ('Indeksy bitmapowe', 1000);
CREATE TABLE PRZYDZIALY(
  ID_PROJEKTU NUMBER(4) NOT NULL CONSTRAINT FK_PRZYDZIALY_01 REFERENCES PROJEKTY(ID_PROJEKTU),
  NR_PRACOWNIKA NUMBER(6) NOT NULL CONSTRAINT FK_PRZYDZIALY_02 REFERENCES PRACOWNICY(ID_PRAC),
  OD DATE DEFAULT CURRENT_DATE,
  DO DATE,
  CONSTRAINT CHK_PRZYDZIALY_DATY CHECK(OD<DO),
  STAWKA NUMBER(7,2) CONSTRAINT CHK_PRZYDZIALY_STAWKA CHECK(STAWKA>0),
  ROLA VARCHAR2(20) CONSTRAINT CHK_PRZYDZIALY_ROLA CHECK(ROLA IN ('KIERUJĄCY', 'ANALITYK', 'PROGRAMISTA'))
);
INSERT INTO PRZYDZIALY(ID_PROJEKTU, NR_PRACOWNIKA, OD, DO, STAWKA, ROLA) VALUES ((SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU='Indeksy bitmapowe'), 170, DATE'1999-04-10', DATE'1999-05-10', 1000, 'KIERUJĄCY');
INSERT INTO PRZYDZIALY(ID_PROJEKTU, NR_PRACOWNIKA, OD, STAWKA, ROLA) VALUES ((SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU='Indeksy bitmapowe'), 140, DATE'2000-12-01', 1500, 'ANALITYK');
INSERT INTO PRZYDZIALY(ID_PROJEKTU, NR_PRACOWNIKA, OD, STAWKA, ROLA) VALUES ((SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU='Sieci kręgosłupowe'), 140, DATE'2015-09-14', 2500, 'KIERUJĄCY');
SELECT * FROM PRZYDZIALY;
ALTER TABLE PRZYDZIALY ADD GODZINY NUMBER(4);
UPDATE PRZYDZIALY SET GODZINY=2111;
ALTER TABLE PRZYDZIALY MODIFY GODZINY NUMBER(4) NOT NULL;
ALTER TABLE PROJEKTY DISABLE CONSTRAINT UK_PROJEKTY;
SELECT CONSTRAINT_NAME, STATUS FROM USER_CONSTRAINTS WHERE TABLE_NAME='PROJEKTY';
INSERT INTO PROJEKTY(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ) VALUES ('Indeksy bitmapowe', DATE'2015-04-12', DATE'2016-09-30', 40000);
ALTER TABLE PROJEKTY ENABLE CONSTRAINT UK_PROJEKTY;
UPDATE PROJEKTY SET OPIS_PROJEKTU='Kesz' WHERE DATA_ROZPOCZECIA=DATE'2015-04-12';
ALTER TABLE PROJEKTY MODIFY OPIS_PROJEKTU VARCHAR2(10);
DELETE FROM PROJEKTY WHERE OPIS_PROJEKTU='Sieci kręgosłupowe';
ALTER TABLE PRZYDZIALY DROP CONSTRAINT FK_PRZYDZIALY_01;
ALTER TABLE PRZYDZIALY MODIFY ID_PROJEKTU NUMBER(4) CONSTRAINT FK_PRZYDZIALY_01 REFERENCES PROJEKTY(ID_PROJEKTU) ON DELETE CASCADE;
DROP TABLE PROJEKTY CASCADE CONSTRAINTS;
DROP TABLE PRZYDZIALY CASCADE CONSTRAINTS;
DROP TABLE PROJEKTY_KOPIA CASCADE CONSTRAINTS;