CREATE OR REPLACE VIEW ASYSTENCI (ID, NAZWISKO, PLACA, STAZ_PRACY) AS SELECT ID_PRAC, NAZWISKO, PLACA_POD, 'lat: '||FLOOR(MONTHS_BETWEEN(CURRENT_DATE, ZATRUDNIONY)/12)||', miesięcy: '|| FLOOR(MOD(MONTHS_BETWEEN(CURRENT_DATE, ZATRUDNIONY), 12)) FROM PRACOWNICY WHERE ETAT='ASYSTENT';
SELECT * FROM ASYSTENCI;
CREATE OR REPLACE VIEW PLACE (ID_ZESP, SREDNIA, MINIMUM, MAXIMUM, FUNDUSZ, L_PENSJI, L_DODATKOW) AS SELECT ID_ZESP, AVG(PLACA_POD+NVL(PLACA_DOD,0)), MIN(PLACA_POD+NVL(PLACA_DOD,0)), MAX(PLACA_POD+NVL(PLACA_DOD,0)), SUM(PLACA_POD+NVL(PLACA_DOD,0)), COUNT(PLACA_POD), COUNT(PLACA_DOD) FROM PRACOWNICY GROUP BY ID_ZESP;
SELECT NAZWISKO, PLACA_POD, SREDNIA FROM PRACOWNICY NATURAL JOIN PLACE WHERE PLACA_POD<SREDNIA ORDER BY PLACA_POD;
CREATE OR REPLACE VIEW PLACE_MINIMALNE (ID_PRAC, NAZWISKO, ETAT, PLACA_POD) AS SELECT ID_PRAC, NAZWISKO, ETAT, PLACA_POD FROM PRACOWNICY WHERE PLACA_POD<700 WITH CHECK OPTION CONSTRAINT za_wysoka_placa;
UPDATE PLACE_MINIMALNE SET PLACE_MINIMALNE.PLACA_POD=1000 WHERE PLACE_MINIMALNE.NAZWISKO = 'KOSZLAJDA';
CREATE OR REPLACE VIEW PRAC_SZEF (ID_PRAC, ID_SZEFA, PRACOWNIK, ETAT, SZEF) AS SELECT p.ID_PRAC, p.ID_SZEFA, p.NAZWISKO, p.ETAT, s.NAZWISKO FROM PRACOWNICY p LEFT JOIN PRACOWNICY s on s.ID_PRAC = p.ID_SZEFA;
SELECt * FROM PRAC_SZEF;
INSERT INTO PRAC_SZEF (ID_PRAC, ID_SZEFA, PRACOWNIK, ETAT) VALUES (280,150, 'MORZY','ASYSTENT');
UPDATE PRAC_SZEF SET ID_SZEFA = 130 WHERE ID_PRAC = 280;
DELETE FROM PRAC_SZEF WHERE ID_PRAC=280;
CREATE OR REPLACE VIEW ZAROBKI(ID_PRAC, NAZWISKO, ETAT, PLACA_POD) AS SELECT p.ID_PRAC, p.NAZWISKO, p.ETAT, p.PLACA_POD FROM PRACOWNICY p LEFT JOIN PRACOWNICY s ON s.ID_PRAC = p.ID_SZEFA WHERE p.PLACA_POD<s.PLACA_POD WITH CHECK OPTION CONSTRAINT WINCYJ;
SELECT * FROM ZAROBKI;
UPDATE ZAROBKI SET PLACA_POD=2000 WHERE NAZWISKO='BIALY'; -- nwm jak zrobić żeby to działało
SELECT * FROM USER_UPDATABLE_COLUMNS WHERE TABLE_NAME='PRAC_SZEF';
